### ISSUE TITLE
No rotation on collision

### ISSUE THREAD

**Issue by gabemolochko** [supereggbert/JigLibJS#3]
Hi, I am creating a bunch of JBoxes and then setting them high above a JPlane. When they fall, they collide with each other and the plane, but they do not rotate. I don't understand why there is no rotation on impact?

I have pasted my code here: http://pastebin.com/gFabjbU6

**Comment by supereggbert** [comment]
get_rotation will only get the last rotation you set if you want the sim orientation you'll need to get the orientation matrix from the current state:
rotmatrix=jig.get_currentState().get_orientation();
