### ISSUE TITLE
Fixed Rotation?

### ISSUE THREAD

**Issue by danielribeiro** [supereggbert/JigLibJS#4]
Is there a way to prevent a body from rotating? This is mostly useful for solid player objects (think zelda in Ocarina of Time).

**Comment by sergiok** [comment]
Hey, have you tried setting set_rotVelocityDamping to 0?
object.set_rotVelocityDamping([0, 0, 0, 0]);

that should prevent that from rotating in any axis.

**Comment by danielribeiro** [comment]
Thanks!
